name: search_gifs_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0' # Certifique-se de que a versão do SDK suporte null safety

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  share: ^2.0.4 # Atualize para uma versão que suporte null safety
  transparent_image: ^2.0.0 # Se não houver uma versão que suporte null safety, considere removê-la
  http: ^0.13.3 # Atualize para a versão mais recente que suporta null safety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
